[package]
name = "xsens-mti"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
static_assertions = "1.1"

[dependencies.byteorder]
version = "1.3"
default-features = false
features = []

[dev-dependencies]
pretty_assertions = "0.6"
serial = "0.4"
ctrlc = "3.1"
